[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "matching-engine"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = ["sortedcontainers"]

[tool.setuptools]
package-dir = {"matching_engine" = "src"} # src folder of matching_engine project exposed to a different name
packages = ["matching_engine"]